# ----
# Site

title: The science behind great cookies, burgers, BBQ and more 
url: "https://www.robbishfood.com"
baseurl: ""
google_analytics_key: G-7GWMYZ8XZ2
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
tagline: BBQ & Food Science
description: Dedicated to all things BBQ and food science (cookies, burgers and mac'n'cheese also feature heavily).
google_site_verification:
author:
  name: Rob Hinds
  email:
  twitter: robhinds
social:
  name: RobbishFood
  links:
    - https://www.instagram.com/robbishfood/

# -----
# Build

timezone: UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "recipe-post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Instagram
  - RSS

_options:
  author_image_webp:
  author_image:
    width: 400
    height: 400
